name: Hello World 2

on:
  push:
    branches:
      - main  # You can change this to any branch you want to trigger the workflow

jobs:
  say-hello:
    runs-on: self-hosted  # This specifies that the job should run on a self-hosted runner
    steps:
      - name: Print Hello
        run: |
          uname -a
          sleep 61
